awslabs/realtime-fraud-detection-with-gnn-on-dgl

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/general-issues.md
=> chore: add issue templates

src/frontend/public/index.html, src/frontend/src/assets/js/const.ts, src/frontend/src/pages/dashboard/Dashboard.tsx, src/frontend/src/pages/dashboard/comps/RealtimeChart.tsx
=> fix: chart data intever with duration time

.github/pull_request_template.md, .projenrc.js
=> chore: update pull request template

src/frontend/src/pages/dashboard/Dashboard.tsx
=> fix: dashboard interval data is wrong when change the duration

src/frontend/src/pages/dashboard/comps/TransactionList.tsx
=> fix: bug fix #19

src/lambda.d/simulator/gen.py
=> fix: the simulator is not properly interrupted

src/frontend/src/App.tsx, src/frontend/src/common/ClientContext.ts, src/frontend/src/pages/dashboard/Dashboard.tsx, src/frontend/src/pages/dashboard/comps/RealtimeChart.tsx
closes #22 and closes #23 
----
=> feat: add more browsers support and token auto renewal

README.md
=> docs: add deployable regions to readme.

.github/workflows/lint-pr.yml
=> ci: update pr lint conf to support dependency bot

.github/workflows/codeql-analysis.yml
=> ci: create codeql-analysis.yml for code scan

.github/workflows/lint-pr.yml
=> ci: update event sources of pr lint

README.md, src/lambda.d/parameters-normalize/index.ts, test/lambda.d/parameters-normalize/index.test.ts
=> chore: polish default hyper-parameters of training job

README.md, src/lambda.d/parameters-normalize/index.ts, src/lib/training-stack.ts, test/lambda.d/parameters-normalize/index.test.ts, test/training-stack.test.ts
=> feat(model): add capability to override default timeout of training

.projen/deps.json, .projen/tasks.json, .projenrc.js, package.json, src/frontend/.projen/deps.json, src/frontend/package.json, src/frontend/yarn.lock, tsconfig.jest.json, yarn.lock
=> chore(deps): bump dependencies

src/frontend/README.md, src/frontend/src/pages/dashboard/Dashboard.tsx, src/frontend/yarn.lock
=> chore: upgrade npm dependencies of frontend

src/lambda.d/parameters-normalize/index.ts, src/lib/training-stack.ts, src/sagemaker/FD_SL_DGL/code/fd_sl_deployment_entry_point.py, test/lambda.d/parameters-normalize/index.test.ts, test/training-stack.test.ts
=> fix: pass the hyperparameter 'n-hidden' of training to inference

.projenrc.js, src/frontend/.projen/deps.json, src/frontend/package.json, src/frontend/yarn.lock
=> fix: ui upgrade react i18next

src/lib/etl-glue.ts, test/training-stack.test.ts
=> chore: use glue 2.0 for China regions

src/lib/dashboard-stack.ts, src/lib/training-stack.ts, test/dashboard-stack.test.ts, test/training-stack.test.ts
=> fix: exceed CloudWatch Logs resource policy size

.github/workflows/bandit-check.yml
=> ci: add bandit check for pr

src/lib/dashboard-stack.ts, src/lib/etl-glue.ts, src/lib/stack.ts, src/lib/training-stack.ts, test/dashboard-stack.test.ts, test/stack.test.ts, test/training-stack.test.ts
=> feat: enable access logging for all s3 buckets

src/lib/stack.ts, test/stack.test.ts
=> feat: configure VPC flow logs for newly created VPC.

src/lib/dashboard-stack.ts, test/dashboard-stack.test.ts
=> feat: enable access log of http api.

src/lib/stack.ts, test/stack.test.ts
- enable minor version update
- config the backup retention to 7 days
closes #72 
----
=> chore: polish Neptune conf

src/lib/dashboard-stack.ts, src/lib/training-stack.ts, test/dashboard-stack.test.ts, test/inference-stack.test.ts, test/training-stack.test.ts
closes #77 
- enable x-ray tracing
----
=> chore: enable x-ray trace for lambda func.

src/lib/stack.ts, test/stack.test.ts
=> feat: specify DLQ for dashboard trans queue

src/lib/etl-glue.ts, test/training-stack.test.ts
- encrypt s3 data at rest
- encrypt cloudwatch logs at rest
- encrypt job bookmark
closes #88 
----
=> feat: add security conf for glue job

src/lib/etl-glue.ts, test/training-stack.test.ts
=> feat: use multiple AZs for glue job

src/lib/dashboard-stack.ts, test/dashboard-stack.test.ts
=> feat: rotate the pass of master user of docdb

src/lib/etl-glue.ts, test/training-stack.test.ts
=> fix: fail on running glue job due to insufficient permission

src/lambda.d/layer.d/awswrangler/requirements.txt, src/lib/dashboard-stack.ts, src/lib/layer.ts, src/lib/training-stack.ts
=> fix: package wrangler layer from its release asset

.projen/tasks.json, .projenrc.js
=> chore: update submodule neptune-utils to support gremlin-python 3.5.0

src/lambda.d/create-indexes/handler.ts
=> fix: delete custom resource of creating indexes of docdb

src/frontend/yarn.lock
=> fix: update ui dependencies

src/lib/dashboard-stack.ts, src/lib/inference-stack.ts, src/lib/training-stack.ts, src/main.ts, test/stack.test.ts
=> chore: tag resources and the description for nested stacks

src/frontend/package.json, src/frontend/yarn.lock
=> fix: update postcss version

src/lambda.d/create-indexes/handler.ts
=> fix: the intermitent deteing failure of createIndex custom resource

.cfn-nag-ignore-lists.yml, .github/workflows/cfn-nag.yml, .projen/deps.json, .projenrc.js, package.json, src/lib/dashboard-stack.ts, src/lib/etl-glue.ts, src/lib/inference-stack.ts, src/lib/sar.ts, src/lib/stack.ts, src/lib/training-stack.ts, src/lib/utils.ts, test/dashboard-stack.test.ts, test/stack.test.ts, test/training-stack.test.ts
=> chore: add cfn_nag scan to ci

docs/index.html, docs/mkdocs.base.yml
=> fix: doc index redirection

.github/workflows/lint-pr.yml, docs/mkdocs.base.yml
=> fix: the language switcher link

docs/mkdocs.base.yml
=> fix: correct the links of lang switcher

docs/mkdocs.base.yml
=> fix: correct the zh lang link of switcher

src/frontend/src/pages/list/List.tsx, src/frontend/yarn.lock
=> fix: update security 0910

.github/workflows/upgrade.yml, .projenrc.js
=> chore: update the token of deps upgrade

README.md
=> docs: add CloudWatch log policy limit to FAQ

.github/workflows/cfn-nag.yml, src/lib/dashboard-stack.ts, src/lib/training-stack.ts, test/dashboard-stack.test.ts
=> chore: improve cfn_nage coverage

.projen/deps.json, .projenrc.js, package.json, yarn.lock
=> chore: bump cdk-bootstrapless-synthesizer

.gitmodules
=> chore: update url of submodule

.projen/deps.json, .projenrc.js, package.json, src/main.ts, yarn.lock
across account ECR in pipeline
----
=> fix: bump cdk-bootstrapless-synthesizer to grant roles for pulling

.projen/deps.json, .projenrc.js, package.json, test/context-provider-mock.ts, test/dashboard-stack.test.ts, test/inference-stack.test.ts, test/stack.test.ts, test/training-stack.test.ts, yarn.lock
=> test: bump test code to new cdk assertions

.github/workflows/ghpage.yml, docs/mkdocs.en.yml, docs/mkdocs.zh.yml
=> docs: fix the links of edit button

src/sagemaker/FD_SL_DGL/code/fd_sl_deployment_entry_point.py
=> docs: fix typo in fd_sl_deployment_entry_point.py

README.md, src/lib/training-stack.ts, test/training-stack.test.ts
=> feat: enable experimental SageMaker serverless inference

.projenrc.js, frontend/package.json, frontend/yarn.lock
=> fix: fix dependabot issues

src/lib/training-stack.ts
=> fix: incorrect serverless inference parameters parsing

.projenrc.js, package.json, src/lambda.d/inference/layer/requirements.txt, src/lambda.d/ingest/import.py, src/lambda.d/layer.d/awswrangler/requirements.txt, src/lib/dashboard-stack.ts, src/lib/inference-stack.ts, src/lib/layer.ts, src/lib/sar.ts, src/lib/training-stack.ts, test/dashboard-stack.test.ts, test/inference-stack.test.ts, test/training-stack.test.ts
also bump to latest Lambda runtime
----
=> fix: grant lambda:TagResource when deploying sar

README.md, docs/en/uninstall.md, docs/zh/uninstall.md
also add blog post in readme
----
=> docs: add 'remove endpoint' in uninstall part

docs/zh/regions.md
=> docs: add cn-north-1 in supported regions to zh docs

src/lib/dashboard-stack.ts
=> fix: update latest documentdb certificate for China regions

.projenrc.js, package.json, src/lib/dashboard-stack.ts, src/lib/inference-stack.ts, src/lib/stack.ts, src/lib/training-stack.ts
=> chore: update sol id

.projen/deps.json, .projen/tasks.json, .projenrc.js, package.json, src/lib/dashboard-stack.ts, src/lib/stack.ts, test/stack.test.ts, test/training-stack.test.ts, yarn.lock
=> fix: explicitly pin neptune engine version to 1.2.0.1

src/lib/training-stack.ts
=> fix: add sagemaker:AddTags to sfn execute role
